# Path to directory containing metagenomic assemblies
assemblydir:
    #"/nfs/research/rdf/escameron/lichen/lichen/results/assembly/spades/public/"
    #"/hps/research/finn/escameron/plastiC/testing/assembly/"
    "tara_scaffolds/"

readdir:
    #"/nfs/research/rdf/escameron/lichen/lichen/results/reads/qc/public/"
    #"/hps/research/finn/escameron/plastiC/testing/reads/"
    "tara_reads/"

# Specify assembly filename (should be identical for each sample)
assemblyname:
  #"spades_output/scaffolds.fasta"
  "scaffolds.fasta"

# Path to directory to contain output results
outputdir:
    "/hps/research/finn/escameron/plastiC/testdrive_tara/"

# Mapping required
maprequire:
  True

# minimum plastid bin content
min_plastid_content:
    90

# Path to CAT database & taxonomy
catdbdir:
    "/hps/research/finn/escameron/databases/CAT_prepare_20210107/2021-01-07_CAT_database/"

cattaxdir:
    "/hps/research/finn/escameron/databases/CAT_prepare_20210107/2021-01-07_taxonomy/"

# Path to Uniref Diamond DB
unirefdb:
  "/hps/research/finn/escameron/checkm2/CheckM2_database/uniref100.KO.1.dmnd"
