# Sample identifiers
# Path to directory containing metagenomic assemblies
assemblydir:
    "/nfs/research/rdf/escameron/lichen/lichen/results/binning/unbinned/private/"

# Specify assembly type: contigs or scaffolds
assemblytype:
  "scaffolds"

# Path to directory containing binning results
bindir:
    "/nfs/research/rdf/escameron/lichen/lichen/results/binning/unbinned/private/"

# Path to directory to contain output results
outputdir:
    "/hps/research/finn/escameron/projects/plastcovery_testing/"
