# Sample identifiers
# Path to directory containing metagenomic assemblies
assemblydir:
    #"/nfs/research/rdf/escameron/lichen/lichen/results/assembly/spades/private/"
    "/hps/research/finn/escameron/plastcovery/testing/assembly/"
readdir:
    #"/nfs/research/rdf/escameron/lichen/lichen/results/reads/qc/private/"
    "/hps/research/finn/escameron/plastcovery/testing/reads/"
# Specify assembly type: contigs or scaffolds
assemblytype:
  "scaffolds"

# Path to directory containing binning results
#bindir:
    #"/nfs/research/rdf/escameron/lichen/lichen/results/binning/private/unbinned/"

# Path to directory to contain output results
outputdir:
    "/hps/research/finn/escameron/plastcovery/testdrive/"

# minimum plastid bin content
min_plastid_content:
    "90"
# Path to CAT database & taxonomy
catdbdir:
    "/hps/research/finn/escameron/databases/CAT_20210107/2021-01-07_database"

cattaxdir:
    "/hps/research/finn/escameron/databases/CAT_20210107/2021-01-07_taxonomy"
