# Path to directory containing metagenomic assemblies
assemblydir:
    "/nfs/research/rdf/escameron/lichen/lichen/results/assembly/spades/private/"
    #"/hps/research/finn/escameron/plastcovery/testing/assembly/"

readdir:
    "/nfs/research/rdf/escameron/lichen/lichen/results/reads/qc/private/"
    #"/hps/research/finn/escameron/plastcovery/testing/reads/"

# Specify assembly type: contigs or scaffolds
assemblytype:
  "scaffolds"

# Path to directory to contain output results
outputdir:
    "/hps/research/finn/escameron/projects/plastcovery_testing/"

# minimum plastid bin content
min_plastid_content:
    90

# Path to CAT database & taxonomy
catdbdir:
    "/hps/research/finn/escameron/databases/CAT_prepare_20210107/2021-01-07_CAT_database/"

cattaxdir:
    "/hps/research/finn/escameron/databases/CAT_prepare_20210107/2021-01-07_taxonomy/"

# Path to Uniref Diamond DB
unirefdb:
  "/hps/research/finn/escameron/checkm2/CheckM2_database/uniref100.KO.1.dmnd"
